create table books
(
    id           int8 generated by default as identity,
    is_converted boolean,
    title        varchar(255),
    primary key (id)
);
create table pages
(
    id          int8 generated by default as identity,
    content     text,
    page_number int4 not null,
    primary key (id)
);
create table users
(
    id       int8 generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
);
create table shelves
(
    id      int8 generated by default as identity,
    name    varchar(255),
    user_id int8,
    primary key (id)
);
create table bookmarks
(
    id         int8 generated by default as identity,
    expired_at timestamp,
    position   int4 not null,
    book_id    int8,
    user_id    int8,
    primary key (id)
);
create table shelves_books
(
    shelf_id int8 not null,
    books_id int8 not null
);
create table books_pages
(
    book_id  int8 not null,
    pages_id int8 not null
);

alter table if exists shelves_books
    add constraint shelves_books_shelves_fk
        foreign key (shelf_id)
            references shelves;

alter table if exists shelves_books
    add constraint shelves_books_books_fk
        foreign key (books_id)
            references books;

alter table if exists shelves
    add constraint shelves_users_fk
        foreign key (user_id)
            references users;

alter table if exists books_pages
    add constraint books_pages_books_fk
        foreign key (book_id)
            references books;

alter table if exists books_pages
    add constraint books_pages_pages_fk
        foreign key (pages_id)
            references pages;

alter table if exists bookmarks
    add constraint bookmarks_users_fk
        foreign key (user_id)
            references users;

alter table if exists bookmarks
    add constraint bookmarks_books_fk
        foreign key (book_id)
            references books;

alter table if exists shelves_books
    add constraint shelves_books_books_uk unique (books_id);

alter table if exists books_pages
    add constraint books_pages_pages_uk unique (pages_id);